#!/bin/sh
echo "🔍 Runtime environment variables:"
echo "--------------------------------"
echo "DATABASE URL:"
echo "$DATABASE_URL"
echo "🔍 Confirming presence of /neon-ca.pem:"
ls -l /neon-ca.pem || echo "❌ Cert file missing!"
echo "🔍 Cert contents:"
head -n 5 /neon-ca.pem || echo "❌ Cannot read cert file!"
echo "--------------------------------"
