services:
  - type: web
    name: vibely-graphql
    runtime: docker
    repo: https://github.com/cwildhorsepv/vibely-graphql.git
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgres://vibely_admin_visitor:pb34e452b55a6fe2a27bcce98f0cf2c28c60a989eb807998d7b4330741ca43e08@ec2-52-70-153-103.compute-1.amazonaws.com:5432/djdhsss5mep4v
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

