services:
    - type: web
      name: vibely-graphql
      runtime: docker
      repo: https://github.com/cwildhorsepv/vibely-graphql.git
      branch: main
      dockerfilePath: ./Dockerfile
      plan: free
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 5000
